FROM resin/%%RESIN_MACHINE_NAME%%-debian

WORKDIR /usr/src/app

RUN    apt-get update \
    && apt-get install \
         git \
         python3 \
         python3-numpy \
         python3-smbus \
         python3-pip \
         python3-rpi.gpio \
    && apt-get clean

COPY requirements.txt ./

RUN pip3 install -r requirements.txt

COPY *.py ./

CMD ["python3", "sensor.py"]
